### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by xjewer**

### CODE REVIEW

**Comment by 2tvenom** [comment]
@xjewer Why close?

**Comment by xjewer** [comment]
I updated `readme.md` with docker image from the my automated build, but if needed i can update readme in PR with [xjewer/go-test-teamcity](https://hub.docker.com/r/xjewer/go-test-teamcity/) image

**Comment by 2tvenom** [comment]
Just add point with docker command in readme. And docker file

**Comment by xjewer** [comment]
i can't reopen PR, so #2

**Pull request closed without merging**
